"""
Mapping from common accord names to weighted representative note profiles.

Weights are 0.0–1.0 and reflect how characteristic the note is for the accord.
"""

ACCORD_NOTES: dict[str, dict[str, float]] = {
    "fresh spicy": {
        "bergamot": 0.8,
        "black pepper": 0.7,
        "ginger": 0.5,
        "cardamom": 0.5,
        "pink pepper": 0.6,
        "lemon": 0.5,
        "geranium": 0.4,
    },
    "woody aromatic": {
        "cedar": 0.8,
        "vetiver": 0.7,
        "sandalwood": 0.6,
        "ambroxan": 0.7,
        "lavender": 0.5,
        "oakmoss": 0.4,
        "guaiac wood": 0.5,
    },
    "oriental gourmand": {
        "vanilla": 0.8,
        "patchouli": 0.7,
        "amber": 0.7,
        "tonka bean": 0.6,
        "benzyl benzoate": 0.5,
        "caramel": 0.6,
        "musk": 0.5,
    },
    "floral aldehyde": {
        "aldehydes": 0.9,
        "rose": 0.7,
        "jasmine": 0.6,
        "iris": 0.6,
        "ylang-ylang": 0.5,
        "bergamot": 0.5,
        "sandalwood": 0.4,
    },
    "fruity chypre": {
        "pineapple": 0.7,
        "apple": 0.6,
        "blackcurrant": 0.6,
        "bergamot": 0.7,
        "rose": 0.5,
        "patchouli": 0.7,
        "oakmoss": 0.6,
    },
    "fresh aquatic": {
        "sea notes": 0.8,
        "bergamot": 0.6,
        "lemon": 0.6,
        "marine": 0.8,
        "musk": 0.5,
        "cedar": 0.4,
        "mint": 0.4,
    },
    "dark floral": {
        "black truffle": 0.6,
        "ylang-ylang": 0.7,
        "rose": 0.7,
        "patchouli": 0.6,
        "incense": 0.5,
        "vetiver": 0.5,
        "blackcurrant": 0.5,
    },
    "citrus": {
        "bergamot": 0.9,
        "lemon": 0.8,
        "mandarin orange": 0.7,
        "grapefruit": 0.7,
        "orange": 0.6,
        "lime": 0.6,
        "neroli": 0.5,
    },
    "oud": {
        "oud": 0.9,
        "rose": 0.6,
        "sandalwood": 0.6,
        "amber": 0.6,
        "incense": 0.5,
        "saffron": 0.5,
        "musk": 0.4,
    },
    "chypre": {
        "oakmoss": 0.8,
        "bergamot": 0.7,
        "labdanum": 0.7,
        "patchouli": 0.6,
        "rose": 0.5,
        "vetiver": 0.5,
        "cistus": 0.4,
    },
    "fougere": {
        "lavender": 0.8,
        "oakmoss": 0.7,
        "coumarin": 0.7,
        "geranium": 0.6,
        "bergamot": 0.5,
        "cedar": 0.5,
        "vetiver": 0.4,
    },
    "powdery": {
        "iris": 0.8,
        "violet": 0.7,
        "musk": 0.7,
        "sandalwood": 0.6,
        "heliotrope": 0.6,
        "vanilla": 0.5,
        "rose": 0.4,
    },
    "leather": {
        "leather": 0.9,
        "birch tar": 0.7,
        "tobacco": 0.6,
        "oud": 0.5,
        "amber": 0.5,
        "vetiver": 0.5,
        "incense": 0.4,
    },
    "green": {
        "galbanum": 0.8,
        "violet leaf": 0.7,
        "grass": 0.6,
        "bergamot": 0.6,
        "jasmine": 0.5,
        "oakmoss": 0.5,
        "cedar": 0.4,
    },
    "musky": {
        "musk": 0.9,
        "ambroxan": 0.7,
        "sandalwood": 0.5,
        "cedarwood": 0.5,
        "white musk": 0.7,
        "tonka bean": 0.4,
    },
    "amber": {
        "amber": 0.9,
        "benzoin": 0.7,
        "labdanum": 0.7,
        "vanilla": 0.6,
        "tonka bean": 0.5,
        "patchouli": 0.5,
        "sandalwood": 0.5,
    },
    "iris": {
        "iris": 0.9,
        "violet": 0.6,
        "rose": 0.5,
        "sandalwood": 0.5,
        "cedarwood": 0.4,
        "musk": 0.4,
        "bergamot": 0.4,
    },
    "rose": {
        "rose": 0.9,
        "geranium": 0.6,
        "patchouli": 0.5,
        "lychee": 0.4,
        "bergamot": 0.5,
        "musk": 0.4,
        "cedar": 0.4,
    },
    "white floral": {
        "jasmine": 0.8,
        "tuberose": 0.7,
        "gardenia": 0.6,
        "ylang-ylang": 0.6,
        "orange blossom": 0.6,
        "musk": 0.5,
        "sandalwood": 0.4,
    },
    "lavender": {
        "lavender": 0.9,
        "bergamot": 0.6,
        "musk": 0.5,
        "coumarin": 0.5,
        "cedar": 0.4,
        "geranium": 0.4,
    },
    "tobacco": {
        "tobacco": 0.9,
        "vanilla": 0.6,
        "leather": 0.5,
        "honey": 0.5,
        "rum": 0.4,
        "cedar": 0.4,
        "amber": 0.5,
    },
    "marine": {
        "marine": 0.9,
        "sea notes": 0.8,
        "bergamot": 0.5,
        "lemon": 0.5,
        "cedar": 0.4,
        "musk": 0.4,
        "ambergris": 0.4,
    },
}
