"""
Mapping from common accord names to weighted representative note profiles.

Used as a fallback in features.py when a perfume has accord tags but no
note pyramid — lets the feature vector reflect accord chemistry rather than
defaulting to generic 5.0 values for all fields.

Weights are 0.0–1.0 and reflect how characteristic the note is for the accord.
Only include notes that exist in notes_chemistry.json so lookups succeed.
"""

ACCORD_NOTES: dict[str, dict[str, float]] = {
    "fresh spicy": {
        "bergamot": 0.7,
        "black pepper": 0.7,
        "ginger": 0.6,
        "cardamom": 0.5,
        "pink pepper": 0.5,
        "coriander": 0.4,
        "lemon": 0.3,
    },
    "warm spicy": {
        "cinnamon": 0.8,
        "clove": 0.7,
        "black pepper": 0.6,
        "cardamom": 0.6,
        "nutmeg": 0.5,
        "amber": 0.4,
        "vanilla": 0.3,
    },
    "spicy": {
        "black pepper": 0.8,
        "cinnamon": 0.6,
        "ginger": 0.6,
        "cardamom": 0.5,
        "clove": 0.5,
        "nutmeg": 0.4,
    },
    "woody aromatic": {
        "cedarwood": 0.8,
        "ambroxan": 0.7,
        "vetiver": 0.6,
        "lavender": 0.5,
        "sandalwood": 0.5,
        "oakmoss": 0.3,
    },
    "aromatic": {
        "lavender": 0.8,
        "geranium": 0.6,
        "rosemary": 0.6,
        "sage": 0.5,
        "bergamot": 0.5,
        "thyme": 0.4,
    },
    "oriental gourmand": {
        "vanilla": 0.8,
        "tonka bean": 0.7,
        "patchouli": 0.6,
        "amber": 0.6,
        "benzoin": 0.5,
        "labdanum": 0.4,
        "caramel": 0.5,
    },
    "gourmand": {
        "vanilla": 0.8,
        "caramel": 0.7,
        "tonka bean": 0.6,
        "praline": 0.6,
        "benzoin": 0.5,
        "sugar": 0.5,
        "chocolate": 0.4,
    },
    "floral aldehyde": {
        "rose": 0.7,
        "jasmine": 0.6,
        "iris": 0.5,
        "aldehydes": 0.7,
        "white musk": 0.5,
        "sandalwood": 0.4,
        "ylang-ylang": 0.4,
    },
    "floral": {
        "rose": 0.7,
        "jasmine": 0.7,
        "peony": 0.6,
        "magnolia": 0.5,
        "gardenia": 0.5,
        "freesia": 0.4,
        "lily": 0.4,
    },
    "fruity chypre": {
        "peach": 0.6,
        "bergamot": 0.6,
        "oakmoss": 0.6,
        "patchouli": 0.5,
        "labdanum": 0.5,
        "rose": 0.4,
    },
    "chypre": {
        "oakmoss": 0.8,
        "labdanum": 0.7,
        "bergamot": 0.6,
        "patchouli": 0.5,
        "rose": 0.4,
        "vetiver": 0.4,
    },
    "fresh aquatic": {
        "sea salt": 0.7,
        "bergamot": 0.6,
        "ambroxan": 0.5,
        "white musk": 0.5,
        "marine accord": 0.6,
        "lemon": 0.4,
    },
    "aquatic": {
        "sea salt": 0.8,
        "ambroxan": 0.5,
        "white musk": 0.5,
        "cucumber": 0.4,
        "bergamot": 0.4,
    },
    "marine": {
        "sea salt": 0.8,
        "ambergris": 0.6,
        "galbanum": 0.5,
        "white musk": 0.5,
        "marine accord": 0.7,
    },
    "dark floral": {
        "jasmine": 0.6,
        "patchouli": 0.6,
        "oud": 0.5,
        "amber": 0.5,
        "rose": 0.4,
        "incense": 0.4,
    },
    "white floral": {
        "tuberose": 0.8,
        "gardenia": 0.7,
        "jasmine": 0.7,
        "ylang-ylang": 0.5,
        "orange blossom": 0.5,
        "white musk": 0.4,
    },
    "citrus": {
        "bergamot": 0.8,
        "lemon": 0.8,
        "grapefruit": 0.7,
        "orange": 0.7,
        "lime": 0.6,
        "yuzu": 0.5,
    },
    "oud": {
        "oud": 0.9,
        "rose": 0.5,
        "saffron": 0.5,
        "sandalwood": 0.5,
        "amber": 0.4,
        "incense": 0.3,
    },
    "fougere": {
        "lavender": 0.8,
        "coumarin": 0.7,
        "oakmoss": 0.6,
        "geranium": 0.5,
        "bergamot": 0.4,
        "vetiver": 0.3,
    },
    "powdery": {
        "iris": 0.8,
        "violet": 0.7,
        "orris root": 0.7,
        "white musk": 0.5,
        "sandalwood": 0.4,
        "heliotrope": 0.5,
    },
    "leather": {
        "leather": 0.9,
        "birch tar": 0.6,
        "vetiver": 0.5,
        "amber": 0.4,
        "tobacco": 0.4,
        "smoky notes": 0.3,
    },
    "green": {
        "galbanum": 0.7,
        "violet leaf": 0.7,
        "grass": 0.6,
        "green tea": 0.6,
        "basil": 0.5,
        "oakmoss": 0.4,
    },
    "musky": {
        "white musk": 0.9,
        "ambroxan": 0.7,
        "musk": 0.8,
        "galaxolide": 0.5,
        "cashmeran": 0.4,
    },
    "amber": {
        "labdanum": 0.8,
        "vanilla": 0.7,
        "benzoin": 0.7,
        "ambergris": 0.6,
        "patchouli": 0.5,
        "sandalwood": 0.4,
    },
    "iris": {
        "iris": 0.9,
        "orris root": 0.8,
        "violet": 0.6,
        "violet leaf": 0.4,
        "sandalwood": 0.3,
    },
    "rose": {
        "rose": 0.9,
        "rose absolute": 0.8,
        "geranium": 0.5,
        "lychee": 0.4,
        "patchouli": 0.3,
    },
    "lavender": {
        "lavender": 0.9,
        "coumarin": 0.5,
        "geranium": 0.4,
        "bergamot": 0.3,
        "tonka bean": 0.3,
    },
    "tobacco": {
        "tobacco": 0.9,
        "vanilla": 0.5,
        "leather": 0.4,
        "labdanum": 0.4,
        "tonka bean": 0.4,
        "rum": 0.3,
    },
    "woody": {
        "cedarwood": 0.8,
        "sandalwood": 0.7,
        "vetiver": 0.6,
        "patchouli": 0.5,
        "oud": 0.4,
        "guaiac wood": 0.4,
    },
    "earthy": {
        "vetiver": 0.8,
        "patchouli": 0.7,
        "oakmoss": 0.6,
        "earth": 0.5,
        "cedarwood": 0.4,
    },
    "resinous": {
        "labdanum": 0.8,
        "benzoin": 0.7,
        "frankincense": 0.7,
        "myrrh": 0.6,
        "opoponax": 0.5,
        "amber": 0.4,
    },
    "balsamic": {
        "benzoin": 0.8,
        "labdanum": 0.7,
        "vanilla": 0.6,
        "peru balsam": 0.6,
        "styrax": 0.5,
    },
    "sweet": {
        "vanilla": 0.8,
        "tonka bean": 0.6,
        "caramel": 0.6,
        "benzoin": 0.5,
        "heliotrope": 0.5,
    },
    "herbal": {
        "lavender": 0.7,
        "rosemary": 0.7,
        "sage": 0.6,
        "thyme": 0.5,
        "basil": 0.5,
        "tarragon": 0.4,
    },
    "fruity": {
        "peach": 0.7,
        "raspberry": 0.7,
        "blackcurrant": 0.6,
        "apple": 0.6,
        "pear": 0.5,
        "bergamot": 0.4,
    },
    "soft spicy": {
        "cardamom": 0.7,
        "pink pepper": 0.6,
        "cinnamon": 0.5,
        "black pepper": 0.5,
        "nutmeg": 0.4,
    },
    "smoky": {
        "vetiver": 0.7,
        "birch tar": 0.6,
        "incense": 0.6,
        "tobacco": 0.5,
        "smoky notes": 0.7,
    },
    "animalic": {
        "musk": 0.8,
        "civet": 0.7,
        "ambergris": 0.6,
        "castoreum": 0.5,
        "leather": 0.4,
    },
    "fresh": {
        "bergamot": 0.7,
        "lemon": 0.6,
        "green tea": 0.5,
        "white musk": 0.5,
        "cucumber": 0.4,
    },
}
